#!/bin/bash

names=$(cat /home/conorpp/bingMiner/names)

while [ 1 ] ; do
    for i in $names
        do
            echo "starting $i"
            t1=`date +%s`
            casperjs --web-security=false worker.js $i d
            casperjs --web-security=false worker.js $i m
            t2=`date +%s`
            echo "Time: " $(( $t2 - $t1 ))
        done
    sleep $(( 60 * 60 ))
done
